- packages/client/src/context/Project.context.tsx
- packages/client/src/graphql/graphql.ts
- packages/client/src/graphql/project/project.graphql
- packages/client/src/graphql/project/project.ts
- packages/client/src/pages/projects/ProjectControl.tsx
- packages/client/src/pages/studies/StudyControl.tsx
- packages/server/schema.gql
- packages/server/src/project/project.module.ts
- packages/server/src/project/project.resolver.ts
- packages/server/src/project/project.service.ts
- packages/server/src/study/study.service.ts
* Delete project
* Impacted studies and tags also deleted
> feat: Project Deletion

- packages/client/src/graphql/graphql.ts
- packages/client/src/graphql/organization/organization.graphql
- packages/client/src/graphql/organization/organization.ts
- packages/client/src/pages/LoginPage.tsx
- packages/server/schema.gql
- packages/server/src/auth/auth.module.ts
- packages/server/src/auth/jwt.strategy.ts
- packages/server/src/organization/dtos/create.dto.ts
- packages/server/src/organization/organization.context.ts
- packages/server/src/organization/organization.model.ts
- packages/server/src/organization/organization.module.ts
- packages/server/src/organization/organization.resolver.ts
- packages/server/src/organization/organization.service.ts
* Support for multi-organization
* Login against different auth projects
* Complete organization context
* `projectId` and `authURL` on `Organization`
> feat: Multi-Organization

- packages/client/src/graphql/graphql.ts
- packages/client/src/graphql/permission/permission.graphql
- packages/client/src/graphql/permission/permission.ts
- packages/client/src/pages/projects/ProjectUserPermissions.tsx
- packages/server/schema.gql
- packages/server/src/permission/permission.resolver.ts
- packages/server/src/permission/permission.service.ts
- packages/server/src/permission/permissions/project.ts
* Changing permission on project
* Project against owner change and self change
> feat: Project Permissions

- packages/client/src/components/NewStudyJsonForm.component.tsx
- packages/client/src/components/TagsDisplay.component.tsx
- packages/client/src/graphql/study/study.graphql
- packages/client/src/graphql/study/study.ts
- packages/client/src/pages/studies/NewStudy.tsx
- packages/client/src/types/study.ts
- packages/server/src/study/study.resolver.ts
> feat: Study Creation

- packages/client/src/components/DatasetsView.component.tsx
- packages/client/src/components/TagTraining.component.tsx
- packages/client/src/graphql/tag.graphql
- packages/client/src/graphql/tag.ts
- packages/client/src/pages/studies/NewStudy.tsx
- packages/server/src/tag/tag.module.ts
- packages/server/src/tag/tag.resolver.ts
* Entry selection on new study
* Creation of tags based on entry selection
* Placeholder for training set selection
> feat: Entry Selection (New Study)

- .gitignore
- packages/client/src/graphql/entry.ts
- packages/client/src/graphql/graphql.ts
- packages/client/src/graphql/project/project.graphql
- packages/client/src/graphql/project/project.ts
- packages/client/src/pages/SuccessPage.tsx
- packages/client/src/pages/projects/NewProject.tsx
- packages/server/.env
* Create project
* Handle create project error
* remove and untrack packages/server/.env
> feat: Project Create (UI)

- packages/client/src/graphql/graphql.ts
- packages/client/src/graphql/permission/permission.graphql
- packages/client/src/graphql/permission/permission.ts
- packages/client/src/pages/datasets/ProjectAccess.tsx
- packages/server/schema.gql
- packages/server/src/dataset/dataset.module.ts
- packages/server/src/dataset/dataset.resolver.ts
- packages/server/src/dataset/dataset.service.ts
- packages/server/src/permission/models/dataset.model.ts
- packages/server/src/permission/permission.module.ts
- packages/server/src/permission/permission.service.ts
- packages/server/src/permission/resolvers/dataset.resolver.ts
* Ability to toggle a project's access to a dataset
* Add named group for project control over dataset
* Query project-dataset access
> feat: Dataset Project Access

- packages/client/src/components/SideBar.component.tsx
- packages/client/src/graphql/graphql.ts
- packages/client/src/graphql/permission/permission.graphql
- packages/client/src/graphql/permission/permission.ts
- packages/server/schema.gql
- packages/server/src/permission/models/permission.model.ts
- packages/server/src/permission/permission.module.ts
- packages/server/src/permission/permission.service.ts
- packages/server/src/permission/resolvers/permission.resolver.ts
* Query for getting roles
* Link visible determined by roles
> feat: Permission based Navigation

- packages/client/src/components/SideBar.component.tsx
- add padding to show full side bar
before fix
after fix
> bug: Add padding to show full side bar

- packages/client/src/components/contribute/TagForm.component.tsx
- packages/client/src/components/tag/videorecord/VideoRecordField.component.tsx
- packages/client/src/context/Tag.context.tsx
- packages/client/src/graphql/graphql.ts
- packages/client/src/graphql/tag/tag.graphql
- packages/client/src/graphql/tag/tag.ts
- packages/client/src/pages/contribute/TaggingInterface.tsx
- packages/server/schema.gql
- packages/server/src/config/configuration.ts
- packages/server/src/tag/models/tag.model.ts
- packages/server/src/tag/models/video-field.model.ts
- packages/server/src/tag/pipes/tag.pipe.ts
- packages/server/src/tag/resolvers/tag.resolver.ts
- packages/server/src/tag/resolvers/video-field.resolver.ts
- packages/server/src/tag/services/tag.service.ts
- packages/server/src/tag/services/video-field.service.ts
- packages/server/src/tag/tag.module.ts
* Creation of video fragments to store incomplete video tags
* Context for Tag to pass the current tag into JSON Forms fields
* UI storage of video fragment section
* UI upload of video to object storage
* No final saving of incomplete video tags
> feat: Video Recording (Backend)

- package-lock.json
- packages/server/package.json
- packages/server/src/study/study.model.ts
- packages/server/src/tag/resolvers/tag.resolver.ts
- packages/server/src/tag/services/tag-transformer.service.ts
- packages/server/src/tag/services/tag.service.ts
- packages/server/src/tag/services/video-field.service.ts
- packages/server/src/tag/tag.module.ts
- packages/server/src/tag/transformers/field-transformer-factory.ts
- packages/server/src/tag/transformers/field-transformer.ts
- packages/server/src/tag/transformers/video-field-transformer.ts
* After a tag is complete, saves the video fields as entries
* Generic tag transformation logic
> feat: Video Saving

- packages/client/src/pages/contribute/ContributeLanding.tsx
- packages/client/src/pages/contribute/TaggingInterface.tsx
- show if there are any tagging left on contribute/landing page
> chore: Simplify contribute and tagging pages

- packages/client/package.json
- packages/client/public/locales/en/translation.json
- packages/client/public/locales/es/translation.json
- packages/client/src/components/Environment.component.tsx
- packages/client/src/components/LanguageSelector.tsx
- packages/client/src/components/SideBar.component.tsx
- packages/client/src/i18n.js
- packages/client/src/main.tsx
- packages/client/src/pages/Home.tsx
- packages/client/src/pages/projects/NewProject.tsx
> feat: Localization

- packages/client/src/App.tsx
- packages/gateway/src/app.module.ts
- packages/server/src/app.module.ts
- packages/server/src/dataset/dataset.module.ts
- packages/server/src/dataset/dataset.resolver.ts
- packages/server/src/entry/entry.module.ts
- packages/server/src/entry/resolvers/entry.resolver.ts
- packages/server/src/jwt/jwt.module.ts
- packages/server/src/jwt/jwt.strategy.ts
- packages/server/src/organization/organization.context.ts
- packages/server/src/organization/organization.guard.ts
- packages/server/src/organization/organization.module.ts
- packages/server/src/permission/permission.module.ts
- packages/server/src/permission/resolvers/permission.resolver.ts
- packages/server/src/project/project.module.ts
- packages/server/src/project/project.resolver.ts
- packages/server/src/userorg/userorg.model.ts
- packages/server/src/userorg/userorg.module.ts
- packages/server/src/userorg/userorg.resolver.ts
- packages/server/src/userorg/userorg.service.ts
* Store `UserOrg` model
* Have organization as request header
* Dedicated Organization Guard
Incomplete
* Have organization selection in UI
> chore: User to Organization Mapping

- packages/server/src/jwt/jwt.guard.ts
- packages/server/src/jwt/jwt.module.ts
- packages/server/src/jwt/jwt.service.ts
- packages/server/src/jwt/jwt.strategy.ts
* Revert to JWT passport strategy
* Leverage `secretOrKeyProvider` functionality
> chore: JWT Cleanup

- packages/client/src/components/SideBar.component.tsx
- packages/server/src/permission/permission.service.ts
- packages/server/src/permission/permissions/project.ts
- packages/server/src/permission/permissions/roles.ts
- packages/server/src/project/project.resolver.ts
- packages/server/src/project/project.service.ts
* Add PROJECT_VIEWER role to bridge gap between study access and project access
> bug: Project List

- packages/client/src/components/TagTraining.component.tsx
- packages/client/src/graphql/graphql.ts
- packages/client/src/graphql/tag/tag.graphql
- packages/client/src/graphql/tag/tag.ts
- packages/client/src/pages/studies/NewStudy.tsx
- packages/server/src/tag/models/tag.model.ts
- packages/server/src/tag/models/training-set.ts
- packages/server/src/tag/resolvers/training-set.resolver.ts
- packages/server/src/tag/services/training-set.service.ts
- packages/server/src/tag/tag.module.ts
* Creation of training set model
* Resolver for making new training sets
* Flag for "training" added to Tag model
* UI code for creating the new training set
> feat: Training Set

- packages/client/public/locales/en/translation.json
- packages/client/src/App.tsx
- packages/client/src/components/SideBar.component.tsx
- packages/client/src/components/TagTraining.component.tsx
- packages/client/src/components/tag/view/TagGridView.component.tsx
- packages/client/src/context/Permission.context.tsx
- packages/client/src/context/Tag.context.tsx
- packages/client/src/graphql/graphql.ts
- packages/client/src/graphql/tag/tag.graphql
- packages/client/src/graphql/tag/tag.ts
- packages/client/src/pages/contribute/ContributeLanding.tsx
- packages/client/src/pages/studies/TagTrainingView.tsx
- packages/client/src/pages/studies/TagView.tsx
- packages/client/src/pages/studies/UserPermissions.tsx
- packages/server/src/tag/resolvers/tag.resolver.ts
- packages/server/src/tag/services/tag.service.ts
- packages/server/src/tag/services/training-set.service.ts
* Ability to complete training in UI
* Study Admin view of training results
> feat: Study Training Results View

- packages/client/src/graphql/tag/tag.graphql
- packages/client/src/graphql/tag/tag.ts
- packages/server/src/config/configuration.ts
- packages/server/src/entry/models/entry.model.ts
- packages/server/src/entry/services/entry.service.ts
- packages/server/src/entry/services/upload-session.service.ts
- packages/server/src/tag/resolvers/tag.resolver.ts
- packages/server/src/tag/services/tag-transformer.service.ts
- packages/server/src/tag/services/tag.service.ts
- packages/server/src/tag/services/video-field.service.ts
- packages/server/src/tag/transformers/field-transformer.ts
- packages/server/src/tag/transformers/video-field-transformer.ts
* Have training videos stored in their own location
* Identification between training and normal videos
> feat: Training Video Storage

- packages/server/src/permission/resolvers/dataset.resolver.ts
* Add needed `toString` on the project and dataset IDs
> bug: Dataset - Project Access

- packages/client/public/locales/en/translation.json
- packages/client/src/App.tsx
- packages/client/src/components/AddDataset.component.tsx
- packages/client/src/components/DatasetTable.component.tsx
- packages/client/src/components/NewStudyJsonForm.component.tsx
- packages/client/src/components/TagTraining.component.tsx
- packages/client/src/components/upload/CSVUpload.component.tsx
- packages/client/src/components/upload/EntryUpload.component.tsx
- packages/client/src/context/Snackbar.context.tsx
- packages/client/src/pages/contribute/TaggingInterface.tsx
- packages/client/src/pages/datasets/ProjectAccess.tsx
- packages/client/src/pages/projects/NewProject.tsx
- packages/client/src/pages/projects/ProjectControl.tsx
- packages/client/src/pages/projects/ProjectUserPermissions.tsx
- packages/client/src/pages/studies/EntryControls.tsx
- packages/client/src/pages/studies/NewStudy.tsx
- packages/client/src/pages/studies/StudyControl.tsx
- packages/client/src/pages/studies/TagTrainingView.tsx
- packages/client/src/pages/studies/UserPermissions.tsx
* Add in Snackbar context
* Attach error messages on GraphQL queries
> chore: UI Error Handling

- packages/server/src/tag/services/tag.service.ts
* Make sure the `training` field is on a newly enabled tag
* Add logic to remove user from disabled tag that is incomplete
> bug: Entry Enabling

- packages/client/public/locales/en/translation.json
- packages/client/src/components/DatasetTable.component.tsx
- packages/client/src/components/DatasetsView.component.tsx
- packages/client/src/pages/datasets/DatasetControls.tsx
* Delete multiple entries at once
* Select all for entry deletion
* Have deletion support be a flag for the dataset view
> feat: Multi-Select Entry Delete

- package-lock.json
- packages/client/src/components/auth/Auth.component.tsx
- packages/client/src/components/auth/Login.component.tsx
- packages/client/src/components/auth/ResetPassword.component.tsx
- packages/client/src/components/auth/Signup.component.tsx
- packages/client/src/context/Auth.context.tsx
* Some cleaning up of the MUI usage
> chore: MUI Cleanup

- package-lock.json
- packages/server/package.json
- packages/server/src/app.module.ts
- packages/server/src/bucket/bucket-factory.service.ts
- packages/server/src/bucket/bucket-info.model.ts
- packages/server/src/bucket/bucket.module.ts
- packages/server/src/bucket/bucket.ts
- packages/server/src/bucket/gcp-bucket.ts
- packages/server/src/entry/entry.module.ts
- packages/server/src/entry/models/upload-session.model.ts
- packages/server/src/entry/services/entry.service.ts
- packages/server/src/entry/services/upload-session.service.ts
- packages/server/src/gcp/gcp.module.ts
- packages/server/src/gcp/providers/secret.provider.ts
- packages/server/src/study/study.module.ts
- packages/server/src/study/study.resolver.ts
- packages/server/src/study/study.service.ts
- packages/server/src/tag/models/video-field.model.ts
- packages/server/src/tag/services/video-field.service.ts
- packages/server/src/tag/tag.module.ts
* Support for each organization to have a dedicated bucket
* Allow for better access control
* Support for different credentials on each bucket
* GCP Secret manager
> feat: Organization Bucket

- packages/client/public/locales/en/translation.json
- packages/client/src/components/AddDataset.component.tsx
- packages/client/src/components/ProjectListSelect.component.tsx
- packages/client/src/components/SideBar.component.tsx
- packages/client/src/context/Dataset.context.tsx
- packages/client/src/graphql/dataset/dataset.graphql
- packages/client/src/graphql/dataset/dataset.ts
- packages/client/src/graphql/entry/entry.graphql
- packages/client/src/graphql/entry/entry.ts
- packages/client/src/graphql/graphql.ts
- packages/client/src/graphql/tag/tag.graphql
- packages/client/src/graphql/tag/tag.ts
- packages/client/src/pages/datasets/DatasetControls.tsx
- packages/server/src/dataset/dataset.resolver.ts
* Can grant project access automatically on dataset creation
* Add refetch method for datasets
> feat: Project Access on Dataset Create

- packages/client/public/locales/en/translation.json
- packages/client/src/components/tag/view/TagGridView.component.tsx
- packages/client/src/components/tag/view/VideoGridView.component.tsx
- packages/client/src/pages/studies/TagView.tsx
* Spacing around video fields
* Toolbar view
* Change name to "Tag View"
> feat: Tag View UI Tweaks

- packages/server/src/download-request/download-request.module.ts
- packages/server/src/download-request/models/dataset-download-request.model.ts
- packages/server/src/download-request/models/study-download-request.model.ts
- packages/server/src/download-request/pipes/dataset-download-request.pipe.ts
- packages/server/src/download-request/pipes/study-download-request.pipe.ts
- packages/server/src/download-request/resolvers/dataset-download-request.resolver.ts
- packages/server/src/download-request/resolvers/study-download-request.resolver.ts
- packages/server/src/download-request/services/dataset-download-request.service.ts
- packages/server/src/download-request/services/study-download-request.service.ts
* Resolvers for handling when a download stage is complete
* Determine if the whole download is ready
> feat: Download Steps

- packages/server/src/config/configuration.ts
- packages/server/src/download-request/resolvers/dataset-download-request.resolver.ts
- packages/server/src/download-request/resolvers/study-download-request.resolver.ts
- packages/server/src/download-request/services/dataset-download-request.service.ts
- packages/server/src/download-request/services/download-request.service.ts
- packages/server/src/download-request/services/study-download-request.service.ts
- packages/zipper/src/commands/zip/index.ts
* Add ability to execute webhook
* Add dataset resolver for webhook
* Add study resolver for webhook
> feat: Webhook Execute

- packages/server/src/download-request/download-request.module.ts
- packages/server/src/download-request/pipes/csv/basic-field.pipe.ts
- packages/server/src/download-request/pipes/csv/video-field.pipe.ts
- packages/server/src/download-request/services/study-download-request.service.ts
- packages/server/src/download-request/types/csv-field.ts
* Handle non-required fields
* Improved formatting
* Extensible method for non-standard data
> bug: Study Tag CSV Download

- packages/client/src/pages/datasets/DatasetDownloads.tsx
- packages/client/src/pages/studies/StudyDownloads.tsx
- packages/server/src/download-request/services/study-download-request.service.ts
* Only allow the download of assets once complete
> bug: Download Progress

- .github/workflows/client.yaml
- .github/workflows/gateway.yaml
- .github/workflows/server.yaml
* GitHub actions for EU Prod deployment
> chore: EU Production

- packages/client/src/components/DatasetTable.component.tsx
- packages/client/src/graphql/entry/entry.graphql
- packages/client/src/graphql/entry/entry.ts
- packages/client/src/graphql/graphql.ts
- packages/server/src/entry/resolvers/entry.resolver.ts
- packages/server/src/entry/services/entry.service.ts
* Add server side pagination for datasets
> bug: Dataset Loading Performance
