ASL-LEX/SignLab2

package-lock.json, packages/client/package.json, packages/client/src/components/contribute/TagForm.component.tsx, packages/client/src/components/tagbuilder/TagFormBuilder.component.tsx, packages/client/src/components/tagbuilder/TagFormPreview.component.tsx, packages/client/src/jsonForms/customRenderes/AslLexSearchControl.tsx, packages/client/src/jsonForms/customRenderes/aslLexSearchControlTester.ts
- Add custom renderer for asllex field
- Show in preview
- Show in tagging
=> feat: Add custom renderer for asllex field

packages/client/src/components/tag/asllex/AslLexSearchControl.tsx, packages/client/src/components/tag/videorecord/VideoRecordField.component.tsx
* Clear ASL-LEX field on submit
* Clear Video field on submit
=> bug: Clear Custom Fields on Submit

packages/client/src/context/Tag.context.tsx
* Handle when the tag is not defined (no more tags available)
=> bug: Final Tag Re-Submit Issue

packages/server/schema.gql, packages/server/src/entry/models/entry.model.ts
* Allow meta data field to be null
* Meta data field possibly null on tags recorded in SignLab
=> bug: Null Metadata

packages/client/src/components/TagTraining.component.tsx
* Have the datasets visible be based on project
=> bug: New Study Correct Datasets

packages/client/src/components/NewStudyJsonForm.component.tsx, packages/client/src/components/tagbuilder/TagField.component.tsx, packages/client/src/components/tagbuilder/TagFormBuilder.component.tsx, packages/client/src/components/tagbuilder/TagProvider.tsx, packages/client/src/pages/studies/NewStudy.tsx
* Reload study meta-data on page change
* Reload tag fields on page change
Incomplete
* Cannot reload selected entries on page change
=> bug: Study Clear

packages/server/src/tag/services/training-set.service.ts
* Delete training set on study deletion
=> feat: Training Set Autodelete

packages/client/src/pages/projects/NewProject.tsx, packages/server/src/project/project.service.ts
* Have submit button be enabled with the form is valid
* Force reload of project permissions for querying
=> bug: Project Create

packages/client/public/locales/en/translation.json, packages/client/src/components/TagTraining.component.tsx
* Add warning for users when no datasets are available for a project
=> feat: Notify on No Datasets

packages/client/src/pages/studies/EntryControls.tsx
* Add notification when no dataset is available
* Disable caching for more dynamic entry control
=> feat: Entry Control No Datasets Available

packages/client/src/pages/contribute/TaggingInterface.tsx
* Update dependency list to not have assign be over triggered
=> bug: Repeat Tag Assign Calls

package-lock.json, packages/client/public/locales/en/translation.json, packages/client/public/locales/es/translation.json, packages/client/src/components/auth/Auth.component.tsx, packages/client/src/components/auth/Login.component.tsx, packages/client/src/components/auth/ResetPassword.component.tsx, packages/client/src/components/auth/Signup.component.tsx, packages/client/src/components/tag/view/TagGridView.component.tsx, packages/client/src/context/Auth.context.tsx, packages/client/src/graphql/graphql.ts, packages/client/src/graphql/tag/tag.graphql, packages/client/src/graphql/tag/tag.ts, packages/client/src/pages/studies/TagTrainingView.tsx, packages/client/src/pages/studies/TagView.tsx, packages/server/src/main.ts, packages/server/src/tag/resolvers/tag.resolver.ts, packages/server/src/tag/services/tag.service.ts
- Completed adding another column at the end of the tag grid with adding in a redo button
- Completed add Mutation and removeTag function to mark the complete tag as incomplete and clear the tag data
- Completed the redo button handle function to trigger removeTag function
- Completed updating the tag GraphQL
=> feat: Tag Visulization Redo

packages/gateway/src/app.module.ts, packages/server/src/tag/resolvers/video-field-inter.resolver.ts
* Allow untrained users to record videos on training tags
* Re-add lex subgraph
=> bug: Training Access

packages/server/src/download-request/services/study-download-request.service.ts
=> feat: User ID Study Download

packages/server/src/entry/resolvers/entry.resolver.ts
* Allow users to resolve entries they have access to
=> bug: Contributor Entry Access

packages/client/src/components/tag/view/VideoGridView.component.tsx, packages/server/src/tag/resolvers/tag.resolver.ts, packages/server/src/tag/services/tag.service.ts
* Correctly display the proper number of columns
* Allow redoing on training tags
=> bug: Video Field

packages/client/src/components/TagTraining.component.tsx
* Allow multi-select for training set
* Allow multi-select for tagging set
=> feat: Dataset Multi-Select

packages/server/src/tag/services/tag.service.ts
* Shuffle entries before making tags
=> feat: Tag Shuffling

.github/workflows/client.yaml, .github/workflows/gateway.yaml, .github/workflows/server.yaml, packages/client/public/locales/en/translation.json, packages/client/src/App.tsx
* Loading screen
* Failed to load screen
=> feat: Loading Screen

packages/client/src/App.tsx, packages/client/src/context/Auth.context.tsx
* Redirect users to login on expired token
=> feat: Auth Redirect

packages/client/src/App.tsx, packages/client/src/components/auth/Auth.component.tsx, packages/client/src/components/auth/Login.component.tsx, packages/client/src/context/Auth.context.tsx, packages/client/src/pages/Home.tsx, packages/client/src/pages/projects/ProjectUserPermissions.tsx, packages/client/src/pages/studies/UserPermissions.tsx
* Remove need to store JWT in local storage
* Allow for refreshing of auth
* Automatic retrieval of user
* Remove GraphQL error link
=> chore: Auth Refresh

packages/client/public/locales/en/translation.json, packages/client/src/components/NewStudyJsonForm.component.tsx, packages/client/src/graphql/graphql.ts, packages/server/src/entry/models/entry.model.ts, packages/server/src/study/dtos/create.dto.ts, packages/server/src/study/study.model.ts, packages/server/src/tag/services/tag.service.ts, packages/server/src/tag/services/video-field-inter.service.ts
* Add ability to filter out users based on entry recording
* Update UI for toggle
=> feat: Config User Self Tagging

package-lock.json, packages/client/public/locales/en/translation.json, packages/client/public/locales/es/translation.json, packages/client/src/graphql/graphql.ts, packages/client/src/graphql/study/study.graphql, packages/client/src/graphql/study/study.ts, packages/client/src/pages/studies/StudyDownloads.tsx, packages/server/package.json, packages/server/src/download-request/download-request.module.ts, packages/server/src/download-request/models/study-download-request.model.ts, packages/server/src/download-request/resolvers/study-download-request.resolver.ts, packages/server/src/download-request/services/study-download-request.service.ts
* User download on study
* Download user ID and user email in CSV format
=> feat: User Download

packages/client/public/locales/en/translation.json, packages/client/public/locales/es/translation.json, packages/client/src/components/tag/asllex/AslLexSearchControl.tsx, packages/client/src/components/tagbuilder/AslLexTagProvider.tsx, packages/client/src/graphql/lex.graphql, packages/client/src/graphql/lex.ts, packages/client/src/pages/studies/NewStudy.tsx, packages/server/src/tag/services/tag-field.service.ts, packages/server/src/tag/transformers/asl-lex-transformer.ts
* Allow the user to select the lexicon in the tag form creation
* Support displaying tags based on the selected lexicon
=> feat: Lexicon Selection Support

packages/client/public/locales/en/translation.json, packages/client/public/locales/en/translation_old.json, packages/client/public/locales/es/translation.json, packages/client/public/locales/es/translation_old.json, packages/client/src/components/contribute/NoTagNotification.component.tsx, packages/client/src/components/tag/videorecord/VideoRecordField.component.tsx
* Bring in new translations
* Fix missing translations elements
=> chore: Update Translations

packages/client/public/locales/es/translation.json
=> chore: Translation Updates

.github/workflows/client.yaml, .github/workflows/gateway.yaml, .github/workflows/server.yaml
=> chore: US Prod

package-lock.json, packages/client/public/locales/en/translation.json, packages/client/public/locales/es/translation.json, packages/client/src/components/NewStudyJsonForm.component.tsx, packages/client/src/graphql/graphql.ts, packages/server/src/study/study.model.ts, packages/server/src/tag/services/tag.service.ts
* Allow user to specify sorting by user provided Entry ID
=> feat: Entry ID Sorting

packages/client/public/locales/en/translation.json, packages/client/src/components/tag/videorecord/VideoRecordField.component.tsx
* Bump video record button
* Tweak text around starting study
=> chore: Video Record Size and Text

packages/client/src/components/contribute/TagForm.component.tsx
=> feat: Enter to Submit

packages/gateway/app.yaml, packages/server/app.yaml
* Bump GCP App Engine Node Version
=> chore: App Node Version Bump

packages/zipper/src/commands/zip/index.ts
* Gracefully handle invalid files when zipping
=> hotfix: Try Catch on Zipper
